---
- name: Create RDS security group
  ec2_group:
    state: present
    name: "{{ cs_app_name }}_sg_rds"
    description: API security group
    vpc_id: "{{ cs_vpc.id }}"
    region: "{{ cs_aws_region }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0
        
- name: Lookup Security Group – RDS
  ec2_group_facts:
    region: "{{ cs_aws_region }}"
    filters: 
      group_name: "{{ cs_app_name }}_sg_rds"
  register:  ec2_group_facts_rds

- name: Capture Security Groups
  set_fact:
    cs_sg_rds: "{{ ec2_group_facts_rds.security_groups[0] }}"
