
---
- rds_subnet_group:
    state: present
    name: "{{ cs_app_name }}_db_subnet"
    region: "{{ cs_aws_region }}"
    description: "{{ cs_app_name }}_db_subnet"
    subnets:
      - "{{ cs_subnet_a.id }}"
      - "{{ cs_subnet_b.id }}"

- name: Create RDS instance
  rds:
    command: create
    instance_name: "{{ cs_database_role }}"
    db_engine: MySQL
    size: '20'
    region: "{{ cs_aws_region }}"
    instance_type: db.t3.micro
    username: "{{ cs_mysql_user }}"
    password: "{{ cs_mysql_password }}"
    publicly_accessible: yes
    subnet: "{{ cs_app_name }}_db_subnet"
    vpc_security_groups: "{{ cs_sg_rds.group_id }}"
    wait: yes
    wait_timeout: 600 #Slow instance creation :(
    tags:
      Role: "{{ cs_database_role }}"