---
- name: Register Secrets for {{ service_name }}
  aws_ssm_parameter_store:
    string_type: SecureString
    region: "{{ cs_aws_region }}"
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ lookup('dict', secrets) }}"

- name: Deploy {{ service_name }}
  serverless:
    stage: prod
    region: "{{ cs_aws_region }}"
    service_path: "/tmp/app/{{ service_name }}"

