---
- name: Initialise resources
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - vpc
    - rds
- name: Deploy serverless functions
  hosts: tag_Role_route53
  connection: local
  roles: 
    - role: database
    - role: serverless 
      vars:
        service_name: cron
        secrets: 
            "route53_mysql_host": "{{ endpoint.address }}"
            "route53_mysql_username": "{{ cs_mysql_user }}"
            "route53_mysql_password": "{{ cs_mysql_password }}"
            "route53_mysql_db_name": "{{ cs_db_name }}"
        security_group: "{{ cs_sg_cron }}"
        subnet: "{{ cs_subnet_a }}"
        role: "{{ cs_app_name}}_cron_iam_role"
    - role: serverless 
      vars:
        service_name: api
        secrets: 
            "route53_mysql_host": "{{ endpoint.address }}"
            "route53_mysql_username": "{{ cs_mysql_user }}"
            "route53_mysql_password": "{{ cs_mysql_password }}"
            "route53_mysql_db_name": "{{ cs_db_name }}"
        security_group: "{{ cs_sg_api }}"
        subnet: "{{ cs_subnet_a }}"
        role: "{{ cs_app_name}}_api_iam_role"
    - role: s3website