service: cron

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:  
      - Effect: Allow
        Action:  
          - route53:Get*
          - route53:List*
          - route53:TestDNSAnswer
        Resource: "*"
functions:
  fn:
    handler: handler.run
    events:
      - schedule: rate(3 hours)
    environment:
      MYSQL_HOST: ${ssm:route53_mysql_host~true}
      MYSQL_DB_NAME: ${ssm:route53_mysql_db_name~true}
      MYSQL_USERNAME: ${ssm:route53_mysql_username~true}
      MYSQL_PASSWORD: ${ssm:route53_mysql_password~true}
  