service: cron

provider:
  name: aws
  runtime: nodejs8.10

functions:
  cron:
    handler: cron.run
    events:
      - schedule: rate(1 minute)
    environment:
      MYSQL_HOST: ${ssm:route53_mysql_host~true}
      MYSQL_DB_NAME: ${ssm:route53_mysql_db_name~true}
      MYSQL_USERNAME: ${ssm:route53_mysql_username~true}
      MYSQL_PASSWORD: ${ssm:route53_mysql_password~true}